    asm `set cur_x 10`;
    asm `set cur_y 10`;
    asm `set font_width 8`;
    asm `set font_height 10`;
    asm `set font_stroke 1`;
    asm `set font_vspace 2`;
    asm `set font_hspace 4`;
    asm `set font_skew 0`;
    asm `op add _drawChar @counter 1`;
    asm `jump draw_char_end always`;
    asm `op div _sk2 font_skew 2`;
    asm `jump draw_char_advance lessThan char 32`;
    asm `jump draw_char_advance greaterThan char 128`;
    asm `op add _xs cur_x _sk2`;
    asm `op add _xss cur_x font_skew`;
    asm `op div _x2 font_width 2`;
    asm `op add _x2 _x2 cur_x`;
    asm `op add _x2s _x2 _sk2`;
    asm `op add _x2ss _x2 font_skew`;
    asm `op add _x3 cur_x font_width`;
    asm `op add _x3s _x3 _sk2`;
    asm `op add _x3ss _x3 font_skew`;
    asm `op div _y2 font_height 2`;
    asm `op add _y2 _y2 cur_y`;
    asm `op add _y3 cur_y font_height`;
    asm `draw stroke font_stroke`;
    asm `op sub _char char 31`;
    asm `op add _char _char @counter`;
    asm `set @counter _char`;
    asm `jump drawChar_32 always`;
    asm `jump drawChar_33 always`;
    asm `jump drawChar_34 always`;
    asm `jump drawChar_35 always`;
    asm `jump drawChar_36 always`;
    asm `jump drawChar_37 always`;
    asm `jump drawChar_38 always`;
    asm `jump drawChar_39 always`;
    asm `jump drawChar_40 always`;
    asm `jump drawChar_41 always`;
    asm `jump drawChar_42 always`;
    asm `jump drawChar_43 always`;
    asm `jump drawChar_44 always`;
    asm `jump drawChar_45 always`;
    asm `jump drawChar_46 always`;
    asm `jump drawChar_47 always`;
    asm `jump drawChar_48 always`;
    asm `jump drawChar_49 always`;
    asm `jump drawChar_50 always`;
    asm `jump drawChar_51 always`;
    asm `jump drawChar_52 always`;
    asm `jump drawChar_53 always`;
    asm `jump drawChar_54 always`;
    asm `jump drawChar_55 always`;
    asm `jump drawChar_56 always`;
    asm `jump drawChar_57 always`;
    asm `jump drawChar_58 always`;
    asm `jump drawChar_59 always`;
    asm `jump drawChar_60 always`;
    asm `jump drawChar_61 always`;
    asm `jump drawChar_62 always`;
    asm `jump drawChar_63 always`;
    asm `jump drawChar_64 always`;
    asm `jump drawChar_65 always`;
    asm `jump drawChar_66 always`;
    asm `jump drawChar_67 always`;
    asm `jump drawChar_68 always`;
    asm `jump drawChar_69 always`;
    asm `jump drawChar_70 always`;
    asm `jump drawChar_71 always`;
    asm `jump drawChar_72 always`;
    asm `jump drawChar_73 always`;
    asm `jump drawChar_74 always`;
    asm `jump drawChar_75 always`;
    asm `jump drawChar_76 always`;
    asm `jump drawChar_77 always`;
    asm `jump drawChar_78 always`;
    asm `jump drawChar_79 always`;
    asm `jump drawChar_80 always`;
    asm `jump drawChar_81 always`;
    asm `jump drawChar_82 always`;
    asm `jump drawChar_83 always`;
    asm `jump drawChar_84 always`;
    asm `jump drawChar_85 always`;
    asm `jump drawChar_86 always`;
    asm `jump drawChar_87 always`;
    asm `jump drawChar_88 always`;
    asm `jump drawChar_89 always`;
    asm `jump drawChar_90 always`;
    asm `jump drawChar_91 always`;
    asm `jump drawChar_92 always`;
    asm `jump drawChar_93 always`;
    asm `jump drawChar_94 always`;
    asm `jump drawChar_95 always`;
    asm `jump drawChar_96 always`;
    asm `jump drawChar_97 always`;
    asm `jump drawChar_98 always`;
    asm `jump drawChar_99 always`;
    asm `jump drawChar_100 always`;
    asm `jump drawChar_101 always`;
    asm `jump drawChar_102 always`;
    asm `jump drawChar_103 always`;
    asm `jump drawChar_104 always`;
    asm `jump drawChar_105 always`;
    asm `jump drawChar_106 always`;
    asm `jump drawChar_107 always`;
    asm `jump drawChar_108 always`;
    asm `jump drawChar_109 always`;
    asm `jump drawChar_110 always`;
    asm `jump drawChar_111 always`;
    asm `jump drawChar_112 always`;
    asm `jump drawChar_113 always`;
    asm `jump drawChar_114 always`;
    asm `jump drawChar_115 always`;
    asm `jump drawChar_116 always`;
    asm `jump drawChar_117 always`;
    asm `jump drawChar_118 always`;
    asm `jump drawChar_119 always`;
    asm `jump drawChar_120 always`;
    asm `jump drawChar_121 always`;
    asm `jump drawChar_122 always`;
    asm `jump drawChar_123 always`;
    asm `jump drawChar_124 always`;
    asm `jump drawChar_125 always`;
    asm `jump drawChar_126 always`;
    asm `jump drawChar_127 always`;
    asm `jump drawChar_128 always`;
    asm `drawChar_32:`;
    asm `jump draw_char_advance always`;
    asm `drawChar_33:`;
    asm `draw line _x3ss _y3 _x3s _y2`;
    asm `draw line _x3s _y2 _x3 cur_y`;
    asm `op add _draw_char_x3 _x3 font_skew`;
    asm `op sub _draw_char_x4 _draw_char_x3 1`;
    asm `draw line _draw_char_x3 cur_y _draw_char_x4 cur_y`;
    asm `jump draw_char_advance always`;
    asm `drawChar_34:`;
    asm `draw line _x3ss _y3 _x3s _y2`;
    asm `draw line _x2ss _y3 _x2s _y2`;
    asm `jump draw_char_advance always`;
    asm `drawChar_35:`;
    asm `draw line _x3ss _y3 _x3s _y2`;
    asm `draw line _x3s _y2 _x3 cur_y`;
    asm `draw line cur_x cur_y _x3 cur_y`;
    asm `draw line _xs _y2 _x2s _y2`;
    asm `draw line _x2s _y2 _x3s _y2`;
    asm `draw line _x2ss _y3 _x2s _y2`;
    asm `draw line _x2 cur_y _x2s _y2`;
    asm `jump draw_char_advance always`;
    asm `drawChar_36:`;
    asm `draw line _xss _y3 _x3ss _y3`;
    asm `draw line _x3s _y2 _x3 cur_y`;
    asm `draw line cur_x cur_y _x3 cur_y`;
    asm `draw line _xss _y3 _xs _y2`;
    asm `draw line _xs _y2 _x2s _y2`;
    asm `draw line _x2s _y2 _x3s _y2`;
    asm `draw line _x2ss _y3 _x2s _y2`;
    asm `draw line _x2 cur_y _x2s _y2`;
    asm `jump draw_char_advance always`;
    asm `drawChar_37:`;
    asm `draw line _x3s _y2 _x3 cur_y`;
    asm `draw line _xss _y3 _xs _y2`;
    asm `draw line _xs _y2 _x2s _y2`;
    asm `draw line _x2s _y2 _x3s _y2`;
    asm `draw line _xss _y3 _x2s _y2`;
    asm `draw line _x2ss _y3 _x2s _y2`;
    asm `draw line _x3ss _y3 _x2s _y2`;
    asm `draw line cur_x cur_y _x2s _y2`;
    asm `draw line _x2 cur_y _x2s _y2`;
    asm `draw line _x2s _y2 _x3 cur_y`;
    asm `jump draw_char_advance always`;
    asm `drawChar_38:`;
    asm `draw line _xss _y3 _x3ss _y3`;
    asm `draw line cur_x cur_y _x3 cur_y`;
    asm `draw line _xs _y2 cur_x cur_y`;
    asm `draw line _xs _y2 _x2s _y2`;
    asm `draw line _xss _y3 _x2s _y2`;
    asm `draw line _x2ss _y3 _x2s _y2`;
    asm `draw line _x2s _y2 _x3 cur_y`;
    asm `jump draw_char_advance always`;
    asm `drawChar_39:`;
    asm `draw line _x2ss _y3 _x2s _y2`;
    asm `jump draw_char_advance always`;
    asm `drawChar_40:`;
    asm `draw line _x3ss _y3 _x2s _y2`;
    asm `draw line _x2s _y2 _x3 cur_y`;
    asm `jump draw_char_advance always`;
    asm `drawChar_41:`;
    asm `draw line _xss _y3 _x2s _y2`;
    asm `draw line cur_x cur_y _x2s _y2`;
    asm `jump draw_char_advance always`;
    asm `drawChar_42:`;
    asm `draw line _xs _y2 _x2s _y2`;
    asm `draw line _x2s _y2 _x3s _y2`;
    asm `draw line _xss _y3 _x2s _y2`;
    asm `draw line _x2ss _y3 _x2s _y2`;
    asm `draw line _x3ss _y3 _x2s _y2`;
    asm `draw line cur_x cur_y _x2s _y2`;
    asm `draw line _x2 cur_y _x2s _y2`;
    asm `draw line _x2s _y2 _x3 cur_y`;
    asm `jump draw_char_advance always`;
    asm `drawChar_43:`;
    asm `draw line _xs _y2 _x2s _y2`;
    asm `draw line _x2s _y2 _x3s _y2`;
    asm `draw line _x2ss _y3 _x2s _y2`;
    asm `draw line _x2 cur_y _x2s _y2`;
    asm `jump draw_char_advance always`;
    asm `drawChar_44:`;
    asm `draw line cur_x cur_y _x2s _y2`;
    asm `jump draw_char_advance always`;
    asm `drawChar_45:`;
    asm `draw line _xs _y2 _x2s _y2`;
    asm `draw line _x2s _y2 _x3s _y2`;
    asm `jump draw_char_advance always`;
    asm `drawChar_46:`;
    asm `op add _draw_char_x3 _x3 font_skew`;
    asm `op sub _draw_char_x4 _draw_char_x3 1`;
    asm `draw line _draw_char_x3 cur_y _draw_char_x4 cur_y`;
    asm `jump draw_char_advance always`;
    asm `drawChar_47:`;
    asm `draw line _x3ss _y3 _x2s _y2`;
    asm `draw line cur_x cur_y _x2s _y2`;
    asm `jump draw_char_advance always`;
    asm `drawChar_48:`;
    asm `draw line _xss _y3 _x3ss _y3`;
    asm `draw line _x3ss _y3 _x3s _y2`;
    asm `draw line _x3s _y2 _x3 cur_y`;
    asm `draw line cur_x cur_y _x3 cur_y`;
    asm `draw line _xs _y2 cur_x cur_y`;
    asm `draw line _xss _y3 _xs _y2`;
    asm `draw line _x3ss _y3 _x2s _y2`;
    asm `draw line cur_x cur_y _x2s _y2`;
    asm `jump draw_char_advance always`;
    asm `drawChar_49:`;
    asm `draw line _x3ss _y3 _x3s _y2`;
    asm `draw line _x3s _y2 _x3 cur_y`;
    asm `draw line _x3ss _y3 _x2s _y2`;
    asm `jump draw_char_advance always`;
    asm `drawChar_50:`;
    asm `draw line _xss _y3 _x3ss _y3`;
    asm `draw line _x3ss _y3 _x3s _y2`;
    asm `draw line cur_x cur_y _x3 cur_y`;
    asm `draw line _xs _y2 cur_x cur_y`;
    asm `draw line _xs _y2 _x2s _y2`;
    asm `draw line _x2s _y2 _x3s _y2`;
    asm `jump draw_char_advance always`;
    asm `drawChar_51:`;
    asm `draw line _xss _y3 _x3ss _y3`;
    asm `draw line _x3ss _y3 _x3s _y2`;
    asm `draw line _x3s _y2 _x3 cur_y`;
    asm `draw line cur_x cur_y _x3 cur_y`;
    asm `draw line _x2s _y2 _x3s _y2`;
    asm `jump draw_char_advance always`;
    asm `drawChar_52:`;
    asm `draw line _x3ss _y3 _x3s _y2`;
    asm `draw line _x3s _y2 _x3 cur_y`;
    asm `draw line _xss _y3 _xs _y2`;
    asm `draw line _xs _y2 _x2s _y2`;
    asm `draw line _x2s _y2 _x3s _y2`;
    asm `jump draw_char_advance always`;
    asm `drawChar_53:`;
    asm `draw line _xss _y3 _x3ss _y3`;
    asm `draw line cur_x cur_y _x3 cur_y`;
    asm `draw line _xss _y3 _xs _y2`;
    asm `draw line _xs _y2 _x2s _y2`;
    asm `draw line _x2s _y2 _x3 cur_y`;
    asm `jump draw_char_advance always`;
    asm `drawChar_54:`;
    asm `draw line _xss _y3 _x3ss _y3`;
    asm `draw line _x3s _y2 _x3 cur_y`;
    asm `draw line cur_x cur_y _x3 cur_y`;
    asm `draw line _xs _y2 cur_x cur_y`;
    asm `draw line _xss _y3 _xs _y2`;
    asm `draw line _xs _y2 _x2s _y2`;
    asm `draw line _x2s _y2 _x3s _y2`;
    asm `jump draw_char_advance always`;
    asm `drawChar_55:`;
    asm `draw line _xss _y3 _x3ss _y3`;
    asm `draw line _x3ss _y3 _x3s _y2`;
    asm `draw line _x3s _y2 _x3 cur_y`;
    asm `jump draw_char_advance always`;
    asm `drawChar_56:`;
    asm `draw line _xss _y3 _x3ss _y3`;
    asm `draw line _x3ss _y3 _x3s _y2`;
    asm `draw line _x3s _y2 _x3 cur_y`;
    asm `draw line cur_x cur_y _x3 cur_y`;
    asm `draw line _xs _y2 cur_x cur_y`;
    asm `draw line _xss _y3 _xs _y2`;
    asm `draw line _xs _y2 _x2s _y2`;
    asm `draw line _x2s _y2 _x3s _y2`;
    asm `jump draw_char_advance always`;
    asm `drawChar_57:`;
    asm `draw line _xss _y3 _x3ss _y3`;
    asm `draw line _x3ss _y3 _x3s _y2`;
    asm `draw line _x3s _y2 _x3 cur_y`;
    asm `draw line cur_x cur_y _x3 cur_y`;
    asm `draw line _xss _y3 _xs _y2`;
    asm `draw line _xs _y2 _x2s _y2`;
    asm `draw line _x2s _y2 _x3s _y2`;
    asm `jump draw_char_advance always`;
    asm `drawChar_58:`;
    asm `draw line _x2ss _y3 _x2s _y2`;
    asm `draw line _x2 cur_y _x2s _y2`;
    asm `jump draw_char_advance always`;
    asm `drawChar_59:`;
    asm `draw line _x2ss _y3 _x2s _y2`;
    asm `draw line cur_x cur_y _x2s _y2`;
    asm `jump draw_char_advance always`;
    asm `drawChar_60:`;
    asm `draw line _xs _y2 _x2s _y2`;
    asm `draw line _x3ss _y3 _x2s _y2`;
    asm `draw line _x2s _y2 _x3 cur_y`;
    asm `jump draw_char_advance always`;
    asm `drawChar_61:`;
    asm `draw line cur_x cur_y _x3 cur_y`;
    asm `draw line _xs _y2 _x2s _y2`;
    asm `draw line _x2s _y2 _x3s _y2`;
    asm `jump draw_char_advance always`;
    asm `drawChar_62:`;
    asm `draw line _x2s _y2 _x3s _y2`;
    asm `draw line _xss _y3 _x2s _y2`;
    asm `draw line cur_x cur_y _x2s _y2`;
    asm `jump draw_char_advance always`;
    asm `drawChar_63:`;
    asm `draw line _xss _y3 _x3ss _y3`;
    asm `draw line _x3ss _y3 _x3s _y2`;
    asm `draw line _x2s _y2 _x3s _y2`;
    asm `draw line _x2 cur_y _x2s _y2`;
    asm `op add _draw_char_x3 _x3 font_skew`;
    asm `op sub _draw_char_x4 _draw_char_x3 1`;
    asm `draw line _draw_char_x3 cur_y _draw_char_x4 cur_y`;
    asm `jump draw_char_advance always`;
    asm `drawChar_64:`;
    asm `draw line _xss _y3 _x3ss _y3`;
    asm `draw line _x3ss _y3 _x3s _y2`;
    asm `draw line cur_x cur_y _x3 cur_y`;
    asm `draw line _xs _y2 cur_x cur_y`;
    asm `draw line _xss _y3 _xs _y2`;
    asm `draw line _x2s _y2 _x3s _y2`;
    asm `draw line _x2ss _y3 _x2s _y2`;
    asm `jump draw_char_advance always`;
    asm `drawChar_65:`;
    asm `draw line _xss _y3 _x3ss _y3`;
    asm `draw line _x3ss _y3 _x3s _y2`;
    asm `draw line _x3s _y2 _x3 cur_y`;
    asm `draw line _xs _y2 cur_x cur_y`;
    asm `draw line _xss _y3 _xs _y2`;
    asm `draw line _xs _y2 _x2s _y2`;
    asm `draw line _x2s _y2 _x3s _y2`;
    asm `jump draw_char_advance always`;
    asm `drawChar_66:`;
    asm `draw line _xss _y3 _x3ss _y3`;
    asm `draw line _x3ss _y3 _x3s _y2`;
    asm `draw line _x3s _y2 _x3 cur_y`;
    asm `draw line cur_x cur_y _x3 cur_y`;
    asm `draw line _x2s _y2 _x3s _y2`;
    asm `draw line _x2ss _y3 _x2s _y2`;
    asm `draw line _x2 cur_y _x2s _y2`;
    asm `jump draw_char_advance always`;
    asm `drawChar_67:`;
    asm `draw line _xss _y3 _x3ss _y3`;
    asm `draw line cur_x cur_y _x3 cur_y`;
    asm `draw line _xs _y2 cur_x cur_y`;
    asm `draw line _xss _y3 _xs _y2`;
    asm `jump draw_char_advance always`;
    asm `drawChar_68:`;
    asm `draw line _xss _y3 _x3ss _y3`;
    asm `draw line _x3ss _y3 _x3s _y2`;
    asm `draw line _x3s _y2 _x3 cur_y`;
    asm `draw line cur_x cur_y _x3 cur_y`;
    asm `draw line _x2ss _y3 _x2s _y2`;
    asm `draw line _x2 cur_y _x2s _y2`;
    asm `jump draw_char_advance always`;
    asm `drawChar_69:`;
    asm `draw line _xss _y3 _x3ss _y3`;
    asm `draw line cur_x cur_y _x3 cur_y`;
    asm `draw line _xs _y2 cur_x cur_y`;
    asm `draw line _xss _y3 _xs _y2`;
    asm `draw line _xs _y2 _x2s _y2`;
    asm `jump draw_char_advance always`;
    asm `drawChar_70:`;
    asm `draw line _xss _y3 _x3ss _y3`;
    asm `draw line _xs _y2 cur_x cur_y`;
    asm `draw line _xss _y3 _xs _y2`;
    asm `draw line _xs _y2 _x2s _y2`;
    asm `jump draw_char_advance always`;
    asm `drawChar_71:`;
    asm `draw line _xss _y3 _x3ss _y3`;
    asm `draw line _x3s _y2 _x3 cur_y`;
    asm `draw line cur_x cur_y _x3 cur_y`;
    asm `draw line _xs _y2 cur_x cur_y`;
    asm `draw line _xss _y3 _xs _y2`;
    asm `draw line _x2s _y2 _x3s _y2`;
    asm `jump draw_char_advance always`;
    asm `drawChar_72:`;
    asm `draw line _x3ss _y3 _x3s _y2`;
    asm `draw line _x3s _y2 _x3 cur_y`;
    asm `draw line _xs _y2 cur_x cur_y`;
    asm `draw line _xss _y3 _xs _y2`;
    asm `draw line _xs _y2 _x2s _y2`;
    asm `draw line _x2s _y2 _x3s _y2`;
    asm `jump draw_char_advance always`;
    asm `drawChar_73:`;
    asm `draw line _xss _y3 _x3ss _y3`;
    asm `draw line cur_x cur_y _x3 cur_y`;
    asm `draw line _x2ss _y3 _x2s _y2`;
    asm `draw line _x2 cur_y _x2s _y2`;
    asm `jump draw_char_advance always`;
    asm `drawChar_74:`;
    asm `draw line _x3ss _y3 _x3s _y2`;
    asm `draw line _x3s _y2 _x3 cur_y`;
    asm `draw line cur_x cur_y _x3 cur_y`;
    asm `draw line _xs _y2 cur_x cur_y`;
    asm `jump draw_char_advance always`;
    asm `drawChar_75:`;
    asm `draw line _xs _y2 cur_x cur_y`;
    asm `draw line _xss _y3 _xs _y2`;
    asm `draw line _xs _y2 _x2s _y2`;
    asm `draw line _x3ss _y3 _x2s _y2`;
    asm `draw line _x2s _y2 _x3 cur_y`;
    asm `jump draw_char_advance always`;
    asm `drawChar_76:`;
    asm `draw line cur_x cur_y _x3 cur_y`;
    asm `draw line _xs _y2 cur_x cur_y`;
    asm `draw line _xss _y3 _xs _y2`;
    asm `jump draw_char_advance always`;
    asm `drawChar_77:`;
    asm `draw line _x3ss _y3 _x3s _y2`;
    asm `draw line _x3s _y2 _x3 cur_y`;
    asm `draw line _xs _y2 cur_x cur_y`;
    asm `draw line _xss _y3 _xs _y2`;
    asm `draw line _xss _y3 _x2s _y2`;
    asm `draw line _x3ss _y3 _x2s _y2`;
    asm `jump draw_char_advance always`;
    asm `drawChar_78:`;
    asm `draw line _x3ss _y3 _x3s _y2`;
    asm `draw line _x3s _y2 _x3 cur_y`;
    asm `draw line _xs _y2 cur_x cur_y`;
    asm `draw line _xss _y3 _xs _y2`;
    asm `draw line _xss _y3 _x2s _y2`;
    asm `draw line _x2s _y2 _x3 cur_y`;
    asm `jump draw_char_advance always`;
    asm `drawChar_79:`;
    asm `draw line _xss _y3 _x3ss _y3`;
    asm `draw line _x3ss _y3 _x3s _y2`;
    asm `draw line _x3s _y2 _x3 cur_y`;
    asm `draw line cur_x cur_y _x3 cur_y`;
    asm `draw line _xs _y2 cur_x cur_y`;
    asm `draw line _xss _y3 _xs _y2`;
    asm `jump draw_char_advance always`;
    asm `drawChar_80:`;
    asm `draw line _xss _y3 _x3ss _y3`;
    asm `draw line _x3ss _y3 _x3s _y2`;
    asm `draw line _xs _y2 cur_x cur_y`;
    asm `draw line _xss _y3 _xs _y2`;
    asm `draw line _xs _y2 _x2s _y2`;
    asm `draw line _x2s _y2 _x3s _y2`;
    asm `jump draw_char_advance always`;
    asm `drawChar_81:`;
    asm `draw line _xss _y3 _x3ss _y3`;
    asm `draw line _x3ss _y3 _x3s _y2`;
    asm `draw line _x3s _y2 _x3 cur_y`;
    asm `draw line cur_x cur_y _x3 cur_y`;
    asm `draw line _xs _y2 cur_x cur_y`;
    asm `draw line _xss _y3 _xs _y2`;
    asm `draw line _x2s _y2 _x3 cur_y`;
    asm `jump draw_char_advance always`;
    asm `drawChar_82:`;
    asm `draw line _xss _y3 _x3ss _y3`;
    asm `draw line _x3ss _y3 _x3s _y2`;
    asm `draw line _xs _y2 cur_x cur_y`;
    asm `draw line _xss _y3 _xs _y2`;
    asm `draw line _xs _y2 _x2s _y2`;
    asm `draw line _x2s _y2 _x3s _y2`;
    asm `draw line _x2s _y2 _x3 cur_y`;
    asm `jump draw_char_advance always`;
    asm `drawChar_83:`;
    asm `draw line _xss _y3 _x3ss _y3`;
    asm `draw line _x3s _y2 _x3 cur_y`;
    asm `draw line cur_x cur_y _x3 cur_y`;
    asm `draw line _xss _y3 _xs _y2`;
    asm `draw line _xs _y2 _x2s _y2`;
    asm `draw line _x2s _y2 _x3s _y2`;
    asm `jump draw_char_advance always`;
    asm `drawChar_84:`;
    asm `draw line _xss _y3 _x3ss _y3`;
    asm `draw line _x2ss _y3 _x2s _y2`;
    asm `draw line _x2 cur_y _x2s _y2`;
    asm `jump draw_char_advance always`;
    asm `drawChar_85:`;
    asm `draw line _x3ss _y3 _x3s _y2`;
    asm `draw line _x3s _y2 _x3 cur_y`;
    asm `draw line cur_x cur_y _x3 cur_y`;
    asm `draw line _xs _y2 cur_x cur_y`;
    asm `draw line _xss _y3 _xs _y2`;
    asm `jump draw_char_advance always`;
    asm `drawChar_86:`;
    asm `draw line _xs _y2 cur_x cur_y`;
    asm `draw line _xss _y3 _xs _y2`;
    asm `draw line _x3ss _y3 _x2s _y2`;
    asm `draw line cur_x cur_y _x2s _y2`;
    asm `jump draw_char_advance always`;
    asm `drawChar_87:`;
    asm `draw line _x3ss _y3 _x3s _y2`;
    asm `draw line _x3s _y2 _x3 cur_y`;
    asm `draw line _xs _y2 cur_x cur_y`;
    asm `draw line _xss _y3 _xs _y2`;
    asm `draw line cur_x cur_y _x2s _y2`;
    asm `draw line _x2s _y2 _x3 cur_y`;
    asm `jump draw_char_advance always`;
    asm `drawChar_88:`;
    asm `draw line _xss _y3 _x2s _y2`;
    asm `draw line _x3ss _y3 _x2s _y2`;
    asm `draw line cur_x cur_y _x2s _y2`;
    asm `draw line _x2s _y2 _x3 cur_y`;
    asm `jump draw_char_advance always`;
    asm `drawChar_89:`;
    asm `draw line _x3ss _y3 _x3s _y2`;
    asm `draw line _x3s _y2 _x3 cur_y`;
    asm `draw line cur_x cur_y _x3 cur_y`;
    asm `draw line _xss _y3 _xs _y2`;
    asm `draw line _xs _y2 _x2s _y2`;
    asm `draw line _x2s _y2 _x3s _y2`;
    asm `jump draw_char_advance always`;
    asm `drawChar_90:`;
    asm `draw line _xss _y3 _x3ss _y3`;
    asm `draw line cur_x cur_y _x3 cur_y`;
    asm `draw line _x3ss _y3 _x2s _y2`;
    asm `draw line cur_x cur_y _x2s _y2`;
    asm `jump draw_char_advance always`;
    asm `drawChar_91:`;
    asm `draw line _xss _y3 _x3ss _y3`;
    asm `draw line cur_x cur_y _x3 cur_y`;
    asm `draw line _xs _y2 cur_x cur_y`;
    asm `draw line _xss _y3 _xs _y2`;
    asm `jump draw_char_advance always`;
    asm `drawChar_92:`;
    asm `draw line _xss _y3 _x2s _y2`;
    asm `draw line _x2s _y2 _x3 cur_y`;
    asm `jump draw_char_advance always`;
    asm `drawChar_93:`;
    asm `draw line _xss _y3 _x3ss _y3`;
    asm `draw line _x3ss _y3 _x3s _y2`;
    asm `draw line _x3s _y2 _x3 cur_y`;
    asm `draw line cur_x cur_y _x3 cur_y`;
    asm `jump draw_char_advance always`;
    asm `drawChar_94:`;
    asm `draw line cur_x cur_y _x2s _y2`;
    asm `draw line _x2s _y2 _x3 cur_y`;
    asm `jump draw_char_advance always`;
    asm `drawChar_95:`;
    asm `draw line cur_x cur_y _x3 cur_y`;
    asm `jump draw_char_advance always`;
    asm `drawChar_96:`;
    asm `draw line _xss _y3 _x2s _y2`;
    asm `jump draw_char_advance always`;
    asm `drawChar_97:`;
    asm `draw line cur_x cur_y _x3 cur_y`;
    asm `draw line _xs _y2 cur_x cur_y`;
    asm `draw line _xs _y2 _x2s _y2`;
    asm `draw line _x2 cur_y _x2s _y2`;
    asm `jump draw_char_advance always`;
    asm `drawChar_98:`;
    asm `draw line cur_x cur_y _x3 cur_y`;
    asm `draw line _xs _y2 cur_x cur_y`;
    asm `draw line _xss _y3 _xs _y2`;
    asm `draw line _xs _y2 _x2s _y2`;
    asm `draw line _x2s _y2 _x3 cur_y`;
    asm `jump draw_char_advance always`;
    asm `drawChar_99:`;
    asm `draw line cur_x cur_y _x3 cur_y`;
    asm `draw line _xs _y2 cur_x cur_y`;
    asm `draw line _xs _y2 _x2s _y2`;
    asm `draw line _x2s _y2 _x3s _y2`;
    asm `jump draw_char_advance always`;
    asm `drawChar_100:`;
    asm `draw line _x3ss _y3 _x3s _y2`;
    asm `draw line _x3s _y2 _x3 cur_y`;
    asm `draw line cur_x cur_y _x3 cur_y`;
    asm `draw line _x2s _y2 _x3s _y2`;
    asm `draw line cur_x cur_y _x2s _y2`;
    asm `jump draw_char_advance always`;
    asm `drawChar_101:`;
    asm `draw line cur_x cur_y _x3 cur_y`;
    asm `draw line _xs _y2 cur_x cur_y`;
    asm `draw line _xs _y2 _x2s _y2`;
    asm `draw line cur_x cur_y _x2s _y2`;
    asm `jump draw_char_advance always`;
    asm `drawChar_102:`;
    asm `draw line _xs _y2 _x2s _y2`;
    asm `draw line _x2s _y2 _x3s _y2`;
    asm `draw line _x3ss _y3 _x2s _y2`;
    asm `draw line _x2 cur_y _x2s _y2`;
    asm `jump draw_char_advance always`;
    asm `drawChar_103:`;
    asm `draw line _x3ss _y3 _x3s _y2`;
    asm `draw line _x3s _y2 _x3 cur_y`;
    asm `draw line cur_x cur_y _x3 cur_y`;
    asm `draw line _x2s _y2 _x3s _y2`;
    asm `draw line _x3ss _y3 _x2s _y2`;
    asm `jump draw_char_advance always`;
    asm `drawChar_104:`;
    asm `draw line _xs _y2 cur_x cur_y`;
    asm `draw line _xss _y3 _xs _y2`;
    asm `draw line _xs _y2 _x2s _y2`;
    asm `draw line _x2 cur_y _x2s _y2`;
    asm `jump draw_char_advance always`;
    asm `drawChar_105:`;
    asm `draw line _x2 cur_y _x2s _y2`;
    asm `jump draw_char_advance always`;
    asm `drawChar_106:`;
    asm `draw line _xs _y2 cur_x cur_y`;
    asm `draw line _x2ss _y3 _x2s _y2`;
    asm `draw line cur_x cur_y _x2s _y2`;
    asm `jump draw_char_advance always`;
    asm `drawChar_107:`;
    asm `draw line _x2ss _y3 _x2s _y2`;
    asm `draw line _x3ss _y3 _x2s _y2`;
    asm `draw line _x2 cur_y _x2s _y2`;
    asm `draw line _x2s _y2 _x3 cur_y`;
    asm `jump draw_char_advance always`;
    asm `drawChar_108:`;
    asm `draw line _xs _y2 cur_x cur_y`;
    asm `draw line _xss _y3 _xs _y2`;
    asm `jump draw_char_advance always`;
    asm `drawChar_109:`;
    asm `draw line _x3s _y2 _x3 cur_y`;
    asm `draw line _xs _y2 cur_x cur_y`;
    asm `draw line _xs _y2 _x2s _y2`;
    asm `draw line _x2s _y2 _x3s _y2`;
    asm `draw line _x2 cur_y _x2s _y2`;
    asm `jump draw_char_advance always`;
    asm `drawChar_110:`;
    asm `draw line _xs _y2 cur_x cur_y`;
    asm `draw line _xs _y2 _x2s _y2`;
    asm `draw line _x2 cur_y _x2s _y2`;
    asm `jump draw_char_advance always`;
    asm `drawChar_111:`;
    asm `draw line _x3s _y2 _x3 cur_y`;
    asm `draw line cur_x cur_y _x3 cur_y`;
    asm `draw line _xs _y2 cur_x cur_y`;
    asm `draw line _xs _y2 _x2s _y2`;
    asm `draw line _x2s _y2 _x3s _y2`;
    asm `jump draw_char_advance always`;
    asm `drawChar_112:`;
    asm `draw line _xs _y2 cur_x cur_y`;
    asm `draw line _xss _y3 _xs _y2`;
    asm `draw line _xs _y2 _x2s _y2`;
    asm `draw line _xss _y3 _x2s _y2`;
    asm `jump draw_char_advance always`;
    asm `drawChar_113:`;
    asm `draw line _x3ss _y3 _x3s _y2`;
    asm `draw line _x3s _y2 _x3 cur_y`;
    asm `draw line _x2s _y2 _x3s _y2`;
    asm `draw line _x3ss _y3 _x2s _y2`;
    asm `jump draw_char_advance always`;
    asm `drawChar_114:`;
    asm `draw line _xs _y2 cur_x cur_y`;
    asm `draw line _xs _y2 _x2s _y2`;
    asm `jump draw_char_advance always`;
    asm `drawChar_115:`;
    asm `draw line cur_x cur_y _x3 cur_y`;
    asm `draw line _x2s _y2 _x3s _y2`;
    asm `draw line _x2s _y2 _x3 cur_y`;
    asm `jump draw_char_advance always`;
    asm `drawChar_116:`;
    asm `draw line cur_x cur_y _x3 cur_y`;
    asm `draw line _xs _y2 cur_x cur_y`;
    asm `draw line _xss _y3 _xs _y2`;
    asm `draw line _xs _y2 _x2s _y2`;
    asm `jump draw_char_advance always`;
    asm `drawChar_117:`;
    asm `draw line _x3s _y2 _x3 cur_y`;
    asm `draw line cur_x cur_y _x3 cur_y`;
    asm `draw line _xs _y2 cur_x cur_y`;
    asm `jump draw_char_advance always`;
    asm `drawChar_118:`;
    asm `draw line _xs _y2 cur_x cur_y`;
    asm `draw line cur_x cur_y _x2s _y2`;
    asm `jump draw_char_advance always`;
    asm `drawChar_119:`;
    asm `draw line _x3s _y2 _x3 cur_y`;
    asm `draw line _xs _y2 cur_x cur_y`;
    asm `draw line cur_x cur_y _x2s _y2`;
    asm `draw line _x2s _y2 _x3 cur_y`;
    asm `jump draw_char_advance always`;
    asm `drawChar_120:`;
    asm `draw line _xss _y3 _x2s _y2`;
    asm `draw line _x3ss _y3 _x2s _y2`;
    asm `draw line cur_x cur_y _x2s _y2`;
    asm `draw line _x2s _y2 _x3 cur_y`;
    asm `jump draw_char_advance always`;
    asm `drawChar_121:`;
    asm `draw line _x3ss _y3 _x3s _y2`;
    asm `draw line _x3s _y2 _x3 cur_y`;
    asm `draw line cur_x cur_y _x3 cur_y`;
    asm `draw line _x2s _y2 _x3s _y2`;
    asm `draw line _x2ss _y3 _x2s _y2`;
    asm `jump draw_char_advance always`;
    asm `drawChar_122:`;
    asm `draw line cur_x cur_y _x3 cur_y`;
    asm `draw line _xs _y2 _x2s _y2`;
    asm `draw line cur_x cur_y _x2s _y2`;
    asm `jump draw_char_advance always`;
    asm `drawChar_123:`;
    asm `draw line _xss _y3 _x3ss _y3`;
    asm `draw line cur_x cur_y _x3 cur_y`;
    asm `draw line _xs _y2 _x2s _y2`;
    asm `draw line _xss _y3 _x2s _y2`;
    asm `draw line cur_x cur_y _x2s _y2`;
    asm `jump draw_char_advance always`;
    asm `drawChar_124:`;
    asm `draw line _x2ss _y3 _x2s _y2`;
    asm `draw line _x2 cur_y _x2s _y2`;
    asm `jump draw_char_advance always`;
    asm `drawChar_125:`;
    asm `draw line _xss _y3 _x3ss _y3`;
    asm `draw line cur_x cur_y _x3 cur_y`;
    asm `draw line _x2s _y2 _x3s _y2`;
    asm `draw line _x3ss _y3 _x2s _y2`;
    asm `draw line _x2s _y2 _x3 cur_y`;
    asm `jump draw_char_advance always`;
    asm `drawChar_126:`;
    asm `draw line _xs _y2 _x2s _y2`;
    asm `draw line _x2s _y2 _x3s _y2`;
    asm `draw line _x3ss _y3 _x2s _y2`;
    asm `draw line cur_x cur_y _x2s _y2`;
    asm `jump draw_char_advance always`;
    asm `drawChar_127:`;
    asm `jump draw_char_advance always`;
    asm `drawChar_128:`;
    asm `jump draw_char_advance always`;
    asm `draw_char_advance:`;
    asm `op add cur_x cur_x font_hspace`;
    asm `op add cur_x cur_x font_width`;
    asm `set @counter _draw_char_return`;
    asm `draw_char_end:`;


